CREATE OR REPLACE TABLE `sandbox-data-pipelines.sales_gold.sales_performance_customers_daily`
(
    date                            DATE,
    month_start_date                DATE,
    quarter_start_date              DATE,
    year_start_date                 DATE,
    customer_id                     INT64,
    customer_company_name           STRING,
    customer_industry               STRING,
    customer_region_id              INT64,
    is_customer_active              BOOLEAN,
    quantity_sold_total             INT64,
    quantity_sold_direct            INT64,
    quantity_sold_distributor       INT64,
    quantity_sold_quantity          INT64,
    quantity_sold_discounted        INT64,
    quantity_returned_total         FLOAT64,
    quantity_returned_direct        FLOAT64,
    quantity_returned_distributor   FLOAT64,
    quantity_returned_online        FLOAT64,
    quantity_returned_discounted    FLOAT64,
    revenue_total                   FLOAT64,
    revenue_direct                  FLOAT64,
    revenue_distributor             FLOAT64,
    revenue_online                  FLOAT64,
    discount_total                  FLOAT64,
    discount_direct                 FLOAT64,
    discount_distributor            FLOAT64,
    discount_online                 FLOAT64,
    gross_profit_total              FLOAT64,
    gross_profit_direct             FLOAT64,
    gross_profit_distributor        FLOAT64,
    gross_profit_online             FLOAT64,
    net_profit_total                FLOAT64,
    net_profit_direct               FLOAT64,
    net_profit_distributor          FLOAT64,
    net_profit_online               FLOAT64,
    execution_ts                    TIMESTAMP,
)
PARTITION BY TIMESTAMP_TRUNC(execution_ts, DAY)
;
